<?php
return array(
    // Settings
        'uniqueId' => '',
        'globalwidth' => 0,
        'image' => '',
        'opacity' => 1,
        'overlaytransitiontime' => 0.5,
        'imagetransitiontime' => 0.5,
        'overlay' => true,
        'imagehvreffect' => 'none',
        'imagehvrfilter' => 'none',
        'imageoverlayouteffect' => 'none',
        'overlaycolor' => 'rgba(106, 111, 248, 0.17)',
        'focalPoint' => array(
            'x' => 0.5,
            'y' => 0.5,
        ),
        'imageborderradiuscircle' => 'square',
        'imagecover' => 'cover',
        'imageaspectratio' => 'original',
        'duotone' => '',
        'showPreview' => false,
        'overlayalignment' => 'center center',
        'overlayalignmenttablet' => 'center center',
        'overlayalignmentmobile' => 'center center',
        'overlayalignmentvertical' => 'center',
        'imagealttext'  => '',

        // image Border
            'imageborder' => array(
                'topcolor' => 'rgb(183, 191, 249)',
                'topwidth' => '2px',
                'topstyle' => 'solid',
                'bottomcolor' => 'rgb(183, 191, 249)',
                'bottomwidth' => '2px',
                'bottomstyle' => 'solid',
                'leftcolor' => 'rgb(183, 191, 249)',
                'leftwidth' => '2px',
                'leftstyle' => 'solid',
                'rightcolor' => 'rgb(183, 191, 249)',
                'rightwidth' => '2px',
                'rightstyle' => 'solid',
            ),
    
        // image Border Radius
            'imageborderRadius' => array(
                'top' => '4px',
                'bottom' => '4px',
                'left' => '4px',
                'right' => '4px',
            ),

        //back setting 
        'backimage' => '',
        'backopacity' => 1,
        'backoverlaycolor' => 'rgba(106, 111, 248, 0.17)',
        'backfocalPoint' => array(
            'x' => 0.5,
            'y' => 0.5,
        ),
        'backimageborderradiuscircle' => 'square',
        'backimagecover' => 'cover',
        'backimageaspectratio' => 'original',
        'backduotone' => '',
        'backoverlayalignment' => 'center center',
        'backoverlayalignmenttablet' => 'center center',
        'backoverlayalignmentmobile' => 'center center',
        'backoverlayalignmentvertical' => 'center',
        'backimagealttext'  => '',

        // image Border
            'backimageborder' => array(
                'topcolor' => 'rgb(183, 191, 249)',
                'topwidth' => '2px',
                'topstyle' => 'solid',
                'bottomcolor' => 'rgb(183, 191, 249)',
                'bottomwidth' => '2px',
                'bottomstyle' => 'solid',
                'leftcolor' => 'rgb(183, 191, 249)',
                'leftwidth' => '2px',
                'leftstyle' => 'solid',
                'rightcolor' => 'rgb(183, 191, 249)',
                'rightwidth' => '2px',
                'rightstyle' => 'solid',
            ),
    
        // image Border Radius
            'backimageborderRadius' => array(
                'top' => '4px',
                'bottom' => '4px',
                'left' => '4px',
                'right' => '4px',
            ),
            'backgroundoption' => 'color',
            'backbackgroundoption' => 'color',

            'imageposition'=> 'center',
            'imagerepeat' => 'no-repeat',
            'backimageposition'=> 'center',
            'backimagerepeat' => 'no-repeat',
        
    //Advanced
        'classNamemain' => '',
        'globalwidth'=> '',
        'width' => '',
        'customWidthlayout' => '',
        'widthType' => 'default',
        'customWidthUnit' => '%',
        'customWidth' => 100,
        'customWidthTablet' => 100,
        'customWidthMobile' => 100,
        'paddingUnit' => 'px',
        'paddingTop' => 0,
        'paddingBottom' => 0,
        'paddingLeft' => 0,
        'paddingRight' => 0,
        'marginUnit' => 'px',
        'marginTop' => 0,
        'marginBottom' => 0,
        'marginLeft' => 0,
        'marginRight' => 0,
        'position' => 'relative',
        'horizontalOrientation' => 'left',
        'horizontalOrientationOffsetUnit' => 'px',
        'horizontalOrientationOffsetRightUnit' => 'px',
        'horizontalOrientationOffset' => 0,
        'horizontalOrientationOffsetRight' => 0,
        'verticalOrientation' => 'top',
        'verticalOrientationOffsetTopUnit' => 'px',
        'verticalOrientationOffsetBottomUnit' => 'px',
        'verticalOrientationOffsetTop' => 0,
        'verticalOrientationOffsetBottom' => 0,
        'zIndex' => 0,
        'selfAlign' => 'start',
        'order' => 'start',
        'customOrder' => 0,
        'flexSize' => 'none',
        'flexGrow' => 1,
        'flexShrink' => 1,
        'borderRadiusType' => 'none',
        'borderRadiusTop' => 4,
        'borderRadiusBottom' => 4,
        'borderRadiusLeft' => 4,
        'borderRadiusRight' => 4,
        'borderRadiusDesktop' => array(
            'topLeft' => 0,
            'topRight' => 0,
            'bottomRight' => 0,
            'bottomLeft' => 0,
        ),
        'borderRadiusTablet' => array(
            'topLeft' => 0,
            'topRight' => 0,
            'bottomRight' => 0,
            'bottomLeft' => 0,
        ),
        'borderRadiusMobile' => array(
            'topLeft' => 0,
            'topRight' => 0,
            'bottomRight' => 0,
            'bottomLeft' => 0,
        ),
        'borderType' => 'none',
        'borderWidthUnit' => 'px',
        'borderWidthTop' => 0,
        'borderWidthBottom' => 0,
        'borderWidthLeft' => 0,
        'borderWidthRight' => 0,
        'borderColor' => '',
        'boxShadow' => false,
        'boxShadowColor' => '',
        'boxShadowColorOpacity' => 50,
        'boxShadowBlur' => 5,
        'boxShadowSpread' => 1,
        'boxShadowHorizontal' => 0,
        'boxShadowVertical' => 0,
        'borderHvrType' => 'none',
        'borderWidthHvrUnit' => 'px',
        'borderWidthHvrTop' => 0,
        'borderWidthHvrBottom' => 0,
        'borderWidthHvrLeft' => 0,
        'borderWidthHvrRight' => 0,
        'borderColorHvr' => '',
        'borderRadiusHvrUnit' => 'px',
        'borderRadiusHvrTop' => 2,
        'borderRadiusHvrBottom' => 2,
        'borderRadiusHvrLeft' => 2,
        'borderRadiusHvrRight' => 2,
        'boxShadowHvr' => false,
        'boxShadowColorHvr' => '',
        'boxShadowColorOpacityHvr' => 50,
        'boxShadowBlurHvr' => 5,
        'boxShadowSpreadHvr' => 1,
        'boxShadowHorizontalHvr' => 0,
        'boxShadowVerticalHvr' => 0,
        'backgroundType' => 'color',
        'backgroundColor' => 'transparent',
        'backgroundImage' => null,
        'backgroundGradient' => 'linear-gradient(135deg,#0F2027 0%, #203A43 0%, #2c5364 100%)',
        'backgroundPosition' => array('x' => 0.5, 'y' => 0.5),
        'backgroundAttachment' => 'scroll',
        'backgroundRepeat' => 'no-repeat',
        'backgroundSize' => 'cover',
        'backgroundTypeHvr' => 'color',
        'backgroundColorHvr' => '',
        'backgroundImageHvr' => null,
        'backgroundGradientHvr' => 'linear-gradient(135deg,#0F2027 0%, #203A43 0%, #2c5364 100%)',
        'backgroundPositionHvr' => array('x' => 0.5, 'y' => 0.5),
        'backgroundAttachmentHvr' => 'scroll',
        'backgroundRepeatHvr' => 'no-repeat',
        'backgroundSizeHvr' => 'cover',
        'transitionAll' => 0,
        'desktopBorderRadiusHvrType' => '',
        'borderRadiusUnit' => 'px',
        'buttonpadding' => 0,
        'buttonpaddingTop' => 0,
        'buttonpaddingRight' => 0,
        'buttonpaddingBottom' => 0,
        'buttonpaddingLeft' => 0,
        'buttonpaddingTablet' => 0,
        'buttonpaddingTopTablet' => 0,
        'buttonpaddingRightTablet' => 0,
        'buttonpaddingBottomTablet' => 0,
        'buttonpaddingLeftTablet' => 0,
        'buttonpaddingMobile' => 0,
        'buttonpaddingTopMobile' => 0,
        'buttonpaddingRightMobile' => 0,
        'buttonpaddingBottomMobile' => 0,
        'buttonpaddingLeftMobile' => 0,
        'marginTopTablet' => 20,
        'marginRightTablet' => 20,
        'marginBottomTablet' => 20,
        'marginLeftTablet' => 20,
        'marginTopMobile' => 20,
        'marginRightMobile' => 20,
        'marginBottomMobile' => 20,
        'marginLeftMobile' => 20,
        'borderradiusTop'=> 0,
        'borderradiusBottom'=> 0,
        'borderradiusLeft'=> 0,
        'borderradiusRight'=> 0,
        'borderradiusTopTablet'=> 20,
        'borderradiusRightTablet'=> 20,
        'borderradiusBottomTablet'=> 20,
        'borderradiusLeftTablet'=> 20,
        'borderradiusTopMobile'=> 20,
        'borderradiusRightMobile'=> 20,
        'borderradiusBottomMobile'=> 20,
        'borderradiusLeftMobile'=> 20,
        'borderradiusHvrTop'=> 0,
        'borderradiusHvrBottom'=> 0,
        'borderradiusHvrLeft'=> 0,
        'borderradiusHvrRight'=> 0,
        'borderradiusHvrTopTablet'=> 20,
        'borderradiusHvrRightTablet'=> 20,
        'borderradiusHvrBottomTablet'=> 20,
        'borderradiusHvrLeftTablet'=> 20,
        'borderradiusHvrTopMobile'=> 20,
        'borderradiusHvrRightMobile'=> 20,
        'borderradiusHvrBottomMobile'=> 20,
        'borderradiusHvrLeftMobile'=> 20,
);
?>
