<?php
return array(
    //edit.json
        'index' => 0,
        'initialSlide' => 0,
        'infinite' => true,
        'centerMode' => false,
        'fade' => false,
        'waitForAnimate' => false,
        'lazyLoad' => false,
        'autoplay' => false,
        'autoplaySpeed' => 3000,
        'pauseOnHover' => false,
        'arrowanimation' => true,
        'focusOnSelect' => false,
        "arrowOnHover" => false,
        'rtl' => false,
        'speed' => 500,
        'slidesToShow' => 1,
        'slidesToScroll' => 1,
        'row' => 1,
        'slidesPerRow' => 1,
        'slidercount' => 2,
        'arrow' => true, // Corrected from string "false" to boolean false
        'customPaging' => false,
        'custompagingvalue' => 0,
        'dots' => array(
            'color' => 'black',
            'backgroundColor' => 'transparent',
            'size' => '16',
            'show' => true,
            'customize' => true,
            'onimage' => false,
            'option' => 'dots',
            'activeColor' => 'gray',
            'position' => 0,
        ),
        'arrowstyleleft' => array(
            'color' => 'white',
            'backgroundColor' => 'gray',
            'backgroundGradient' => 'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)',
            'size' => '20px',
            'tag' => 'arrow',
            'position' => 0,
            'borderRadius' => array(
                'top' => '50px',
                'right' => '50px',
                'bottom' => '50px',
                'left' => '50px',
            ),
        ),
        'slides' => array(
            array(
                'layout' => array(
                    'uniqueId' => 'slide-default-1',
                    'button1' => array(
                        'show' => true,
                        'text' => 'button 1',
                        'link' => '',
                        'newtab' => true,
                        'size' => 20,
                        'backgroundColor' => 'blue',
                        'backgroundType' => 'color',
                        'backgroundGradient' => 'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)',
                        'color' => 'white',
                        'border' => array(
                            'color' => 'white',
                            'width' => '1px',
                            'style' => 'solid',
                            'topcolor' => 'white',
                            'topwidth' => '1px',
                            'topstyle' => 'solid',
                            'bottomcolor' => 'white',
                            'bottomwidth' => '1px',
                            'bottomstyle' => 'solid',
                            'leftcolor' => 'white',
                            'leftwidth' => '1px',
                            'leftstyle' => 'solid',
                            'rightcolor' => 'white',
                            'rightwidth' => '1px',
                            'rightstyle' => 'solid',
                        ),
                        'borderRadius' => array(
                            'top' => '5px',
                            'right' => '5px',
                            'bottom' => '5px',
                            'left' => '5px',
                        ),
                        'padding' => array(
                            'top' => '10px',
                            'right' => '20px',
                            'bottom' => '10px',
                            'left' => '20px',
                        ),
                    ),
                    'button2' => array(
                        'show' => true,
                        'link' => '',
                        'newtab' => true,
                        'text' => 'button 2',
                        'size' => 20,
                        'backgroundColor' => 'blue',
                        'backgroundType' => 'color',
                        'backgroundGradient' => 'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)',
                        'color' => 'white',
                        'border' => array(
                            'color' => 'white',
                            'width' => '1px',
                            'style' => 'solid',
                            'topcolor' => 'white',
                            'topwidth' => '1px',
                            'topstyle' => 'solid',
                            'bottomcolor' => 'white',
                            'bottomwidth' => '1px',
                            'bottomstyle' => 'solid',
                            'leftcolor' => 'white',
                            'leftwidth' => '1px',
                            'leftstyle' => 'solid',
                            'rightcolor' => 'white',
                            'rightwidth' => '1px',
                            'rightstyle' => 'solid',
                        ),
                        'borderRadius' => array(
                            'top' => '5px',
                            'right' => '5px',
                            'bottom' => '5px',
                            'left' => '5px',
                        ),
                        'padding' => array(
                            'top' => '10px',
                            'right' => '20px',
                            'bottom' => '10px',
                            'left' => '20px',
                        ),
                    ),
                    'heading' => array(
                        'text' => 'Slider',
                        'tag' => 'h2',
                        'newtab' => true,
                        'size' => 28,
                        'fontWeight' => 'bold',
                        'color' => 'black',
                        'link' => '',
                    ),
                    'subheading' => array(
                        'show' => true,
                        'text' => 'lorem sub heading for oout topic has ben very important.',
                        'tag' => 'h4',
                        'size' => 16,
                        'fontWeight' => 'lighter',
                        'color' => 'black',
                        'link' => '',
                        'newtab' => true,
                    ),
                    'border' => array(
                        'color' => 'black',
                        'width' => '1px',
                        'style' => 'solid',
                        'topcolor' => 'black',
                        'topwidth' => '1px',
                        'topstyle' => 'solid',
                        'bottomcolor' => 'black',
                        'bottomwidth' => '1px',
                        'bottomstyle' => 'solid',
                        'leftcolor' => 'black',
                        'leftwidth' => '1px',
                        'leftstyle' => 'solid',
                        'rightcolor' => 'black',
                        'rightwidth' => '1px',
                        'rightstyle' => 'solid',
                    ),
                    'borderRadius' => array(
                        'top' => '5px',
                        'right' => '5px',
                        'bottom' => '5px',
                        'left' => '5px',
                    ),
                    'padding' => array(
                        'top' => '0px',
                        'right' => '0px',
                        'bottom' => '0px',
                        'left' => '0px',
                    ),
                    'opacity' => 0.2,
                    'backgroundBlend' => 'lighten',
                    'backgroundImage' => '',
                    'focalPoint' => array(
                        'x' => 0.5,
                        'y' => 0.5,
                    ),
                    'duotone'=> '',
                    'backgroundType' => 'color',
                    'backgroundColor' => '#000000',
                    'backgroundGradient' => 'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)',
                    'alignment' => 'center',
                ),
            ),
            array(
                'layout' => array(
                    'uniqueId' => 'slide-default-2',
                    'button1' => array(
                        'show' => true,
                        'text' => 'button 1',
                        'link' => '',
                        'newtab' => true,
                        'size' => 20,
                        'backgroundColor' => 'blue',
                        'backgroundType' => 'color',
                        'backgroundGradient' => 'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)',
                        'color' => 'white',
                        'border' => array(
                            'color' => 'white',
                            'width' => '1px',
                            'style' => 'solid',
                            'topcolor' => 'white',
                            'topwidth' => '1px',
                            'topstyle' => 'solid',
                            'bottomcolor' => 'white',
                            'bottomwidth' => '1px',
                            'bottomstyle' => 'solid',
                            'leftcolor' => 'white',
                            'leftwidth' => '1px',
                            'leftstyle' => 'solid',
                            'rightcolor' => 'white',
                            'rightwidth' => '1px',
                            'rightstyle' => 'solid',
                        ),
                        'borderRadius' => array(
                            'top' => '5px',
                            'right' => '5px',
                            'bottom' => '5px',
                            'left' => '5px',
                        ),
                        'padding' => array(
                            'top' => '10px',
                            'right' => '20px',
                            'bottom' => '10px',
                            'left' => '20px',
                        ),
                    ),
                    'button2' => array(
                        'show' => true,
                        'link' => '',
                        'newtab' => true,
                        'text' => 'button 2',
                        'size' => 20,
                        'backgroundColor' => 'blue',
                        'backgroundType' => 'color',
                        'backgroundGradient' => 'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)',
                        'color' => 'white',
                        'border' => array(
                            'color' => 'white',
                            'width' => '1px',
                            'style' => 'solid',
                            'topcolor' => 'white',
                            'topwidth' => '1px',
                            'topstyle' => 'solid',
                            'bottomcolor' => 'white',
                            'bottomwidth' => '1px',
                            'bottomstyle' => 'solid',
                            'leftcolor' => 'white',
                            'leftwidth' => '1px',
                            'leftstyle' => 'solid',
                            'rightcolor' => 'white',
                            'rightwidth' => '1px',
                            'rightstyle' => 'solid',
                        ),
                        'borderRadius' => array(
                            'top' => '5px',
                            'right' => '5px',
                            'bottom' => '5px',
                            'left' => '5px',
                        ),
                        'padding' => array(
                            'top' => '10px',
                            'right' => '20px',
                            'bottom' => '10px',
                            'left' => '20px',
                        ),
                    ),
                    'heading' => array(
                        'text' => 'Slider',
                        'tag' => 'h2',
                        'newtab' => true,
                        'size' => 28,
                        'fontWeight' => 'bold',
                        'color' => 'black',
                        'link' => '',
                    ),
                    'subheading' => array(
                        'show' => true,
                        'text' => 'lorem sub heading for oout topic has ben very important.',
                        'tag' => 'h4',
                        'size' => 16,
                        'fontWeight' => 'lighter',
                        'color' => 'black',
                        'link' => '',
                        'newtab' => true,
                    ),
                    'border' => array(
                        'color' => 'black',
                        'width' => '1px',
                        'style' => 'solid',
                        'topcolor' => 'black',
                        'topwidth' => '1px',
                        'topstyle' => 'solid',
                        'bottomcolor' => 'black',
                        'bottomwidth' => '1px',
                        'bottomstyle' => 'solid',
                        'leftcolor' => 'black',
                        'leftwidth' => '1px',
                        'leftstyle' => 'solid',
                        'rightcolor' => 'black',
                        'rightwidth' => '1px',
                        'rightstyle' => 'solid',
                    ),
                    'borderRadius' => array(
                        'top' => '5px',
                        'right' => '5px',
                        'bottom' => '5px',
                        'left' => '5px',
                    ),
                    'padding' => array(
                        'top' => '0px',
                        'right' => '0px',
                        'bottom' => '0px',
                        'left' => '0px',
                    ),
                    'opacity' => 0.2,
                    'backgroundBlend' => 'lighten',
                    'backgroundImage' => '',
                    'focalPoint' => array(
                        'x' => 0.5,
                        'y' => 0.5,
                    ),
                    'duotone'=> '',
                    'backgroundType' => 'color',
                    'backgroundColor' => '#000000',
                    'backgroundGradient' => 'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)',
                    'alignment' => 'center',
                ),
            ),
        ),

    //Advanced
        'globalwidth'=> '',
        'width' => '',
        'customWidthlayout' => '',
        'widthType' => 'default',
        'customWidthUnit' => '%',
        'customWidth' => 100,
        'customWidthTablet' => 100,
        'customWidthMobile' => 100,
        'paddingUnit' => 'px',
        'paddingTop' => 0,
        'paddingBottom' => 0,
        'paddingLeft' => 0,
        'paddingRight' => 0,
        'marginUnit' => 'px',
        'marginTop' => 0,
        'marginBottom' => 0,
        'marginLeft' => 0,
        'marginRight' => 0,
        'position' => 'relative',
        'horizontalOrientation' => 'left',
        'horizontalOrientationOffsetUnit' => 'px',
        'horizontalOrientationOffsetRightUnit' => 'px',
        'horizontalOrientationOffset' => 0,
        'horizontalOrientationOffsetRight' => 0,
        'verticalOrientation' => 'top',
        'verticalOrientationOffsetTopUnit' => 'px',
        'verticalOrientationOffsetBottomUnit' => 'px',
        'verticalOrientationOffsetTop' => 0,
        'verticalOrientationOffsetBottom' => 0,
        'zIndex' => 0,
        'selfAlign' => 'start',
        'order' => 'start',
        'customOrder' => 0,
        'flexSize' => 'none',
        'flexGrow' => 1,
        'flexShrink' => 1,
        'borderRadiusType' => 'none',
        'borderRadiusTop' => 4,
        'borderRadiusBottom' => 4,
        'borderRadiusLeft' => 4,
        'borderRadiusRight' => 4,
        'borderRadiusDesktop' => array(
            'topLeft' => 0,
            'topRight' => 0,
            'bottomRight' => 0,
            'bottomLeft' => 0,
        ),
        'borderRadiusTablet' => array(
            'topLeft' => 0,
            'topRight' => 0,
            'bottomRight' => 0,
            'bottomLeft' => 0,
        ),
        'borderRadiusMobile' => array(
            'topLeft' => 0,
            'topRight' => 0,
            'bottomRight' => 0,
            'bottomLeft' => 0,
        ),
        'borderType' => 'none',
        'borderWidthUnit' => 'px',
        'borderWidthTop' => 0,
        'borderWidthBottom' => 0,
        'borderWidthLeft' => 0,
        'borderWidthRight' => 0,
        'borderColor' => '',
        'boxShadow' => false,
        'boxShadowColor' => '',
        'boxShadowColorOpacity' => 50,
        'boxShadowBlur' => 5,
        'boxShadowSpread' => 1,
        'boxShadowHorizontal' => 0,
        'boxShadowVertical' => 0,
        'borderHvrType' => 'none',
        'borderWidthHvrUnit' => 'px',
        'borderWidthHvrTop' => 0,
        'borderWidthHvrBottom' => 0,
        'borderWidthHvrLeft' => 0,
        'borderWidthHvrRight' => 0,
        'borderColorHvr' => '',
        'borderRadiusHvrUnit' => 'px',
        'borderRadiusHvrTop' => 2,
        'borderRadiusHvrBottom' => 2,
        'borderRadiusHvrLeft' => 2,
        'borderRadiusHvrRight' => 2,
        'boxShadowHvr' => false,
        'boxShadowColorHvr' => '',
        'boxShadowColorOpacityHvr' => 50,
        'boxShadowBlurHvr' => 5,
        'boxShadowSpreadHvr' => 1,
        'boxShadowHorizontalHvr' => 0,
        'boxShadowVerticalHvr' => 0,
        'backgroundType' => 'color',
        'backgroundColor' => 'transparent',
        'backgroundImage' => null,
        'backgroundGradient' => 'linear-gradient(135deg,#0F2027 0%, #203A43 0%, #2c5364 100%)',
        'backgroundPosition' => array('x' => 0.5, 'y' => 0.5),
        'backgroundAttachment' => 'scroll',
        'backgroundRepeat' => 'no-repeat',
        'backgroundSize' => 'cover',
        'backgroundTypeHvr' => 'color',
        'backgroundColorHvr' => '',
        'backgroundImageHvr' => null,
        'backgroundGradientHvr' => 'linear-gradient(135deg,#0F2027 0%, #203A43 0%, #2c5364 100%)',
        'backgroundPositionHvr' => array('x' => 0.5, 'y' => 0.5),
        'backgroundAttachmentHvr' => 'scroll',
        'backgroundRepeatHvr' => 'no-repeat',
        'backgroundSizeHvr' => 'cover',
        'transitionAll' => 0,
        'desktopBorderRadiusHvrType' => '',
        'borderRadiusUnit' => 'px',
        'buttonpadding' => 0,
        'buttonpaddingTop' => 0,
        'buttonpaddingRight' => 0,
        'buttonpaddingBottom' => 0,
        'buttonpaddingLeft' => 0,
        'buttonpaddingTablet' => 0,
        'buttonpaddingTopTablet' => 0,
        'buttonpaddingRightTablet' => 0,
        'buttonpaddingBottomTablet' => 0,
        'buttonpaddingLeftTablet' => 0,
        'buttonpaddingMobile' => 0,
        'buttonpaddingTopMobile' => 0,
        'buttonpaddingRightMobile' => 0,
        'buttonpaddingBottomMobile' => 0,
        'buttonpaddingLeftMobile' => 0,
        'marginTopTablet' => 20,
        'marginRightTablet' => 20,
        'marginBottomTablet' => 20,
        'marginLeftTablet' => 20,
        'marginTopMobile' => 20,
        'marginRightMobile' => 20,
        'marginBottomMobile' => 20,
        'marginLeftMobile' => 20,
        'borderradiusTop'=> 0,
        'borderradiusBottom'=> 0,
        'borderradiusLeft'=> 0,
        'borderradiusRight'=> 0,
        'borderradiusTopTablet'=> 20,
        'borderradiusRightTablet'=> 20,
        'borderradiusBottomTablet'=> 20,
        'borderradiusLeftTablet'=> 20,
        'borderradiusTopMobile'=> 20,
        'borderradiusRightMobile'=> 20,
        'borderradiusBottomMobile'=> 20,
        'borderradiusLeftMobile'=> 20,
        'borderradiusHvrTop'=> 0,
        'borderradiusHvrBottom'=> 0,
        'borderradiusHvrLeft'=> 0,
        'borderradiusHvrRight'=> 0,
        'borderradiusHvrTopTablet'=> 20,
        'borderradiusHvrRightTablet'=> 20,
        'borderradiusHvrBottomTablet'=> 20,
        'borderradiusHvrLeftTablet'=> 20,
        'borderradiusHvrTopMobile'=> 20,
        'borderradiusHvrRightMobile'=> 20,
        'borderradiusHvrBottomMobile'=> 20,
        'borderradiusHvrLeftMobile'=> 20,
);
?>
